(define-module (extra goose)
  :use-module (srfi srfi-1)
  :use-module (srfi srfi-2)
  :use-module (srfi srfi-11)
  :use-module (oop goops)
  :use-module (ice-9 match)
  :use-module (ice-9 optargs)
  :use-module (extra slayer)
  :use-module (extra ref)
  :use-module (extra common)
  :use-module (extra network)
  :use-module ((rnrs) :version (6))
  :export (<goose>))

(define-class <goose> ()
  (owners #:init-value #f #:init-keyword #:owners)
  (private-slots #:init-value '())
  (id #:init-thunk gensym))
